### ISSUE TITLE
página «involucrarse»

### ISSUE THREAD

**Issue by 51114u9** [RipeAtlasBolivia/atlas.tecnologia.bo#2]
Vendría bien crear una página llamada «involucrarse» que muestre cómo colaborar con ripe atlas, algo así:

[Albergar una sonda (probe)], breve explicación y enlace a solicitar una sonda
[Albergar un anclaje (anchor)], breve explicación
[Comunidad Ripe Atlas], quizá enlace a lista de correo

entre hoy y mañana mando PR con esta página

**Comment by severo** [comment]
¡Gracias por la idea @51114u9! Cualquier mejora a la página, adelante. https://atlas.tecnologia.bo/involucrarse/
